#!/bin/sh

# Executed by startx (run your window manager from here)
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -s ~/.Xmodmap ]; then
  xmodmap ~/.Xmodmap
fi

nm-applet &
tmux new -d -s "home" &
greenclip daemon &
thunar --daemon &
redshift-gtk &
nextcloud &

# exec bspwm

# XFCE only {{{

# set mouse to center of monitor 1
xdotool mousemove 960 540 &

# to disable beep on logout
# source: https://forum.xfce.org/viewtopic.php?pid=45828#p45828
xset b off &

exec startxfce4
# }}}
