#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

nm-applet &
blueman-applet &
tmux new -d -s home \; send -R "cal -3w" Enter &
greenclip daemon &
thunar --daemon &
redshift-gtk -l 52.520008:13.404954 &
notion-app-enhanced &
# ./Notion-linux-x64/Notion &
flameshot &
hushboard &
typora /home/dan/Cloud.rocks/plan.md &

# exec bspwm

# XFCE only {{{

# set mouse to center of monitor 1
xdotool mousemove 960 540 &

# to disable beep on logout
# source: https://forum.xfce.org/viewtopic.php?pid=45828#p45828
xset b off &

exec startxfce4
# }}}
