#!/bin/sh

if [ -f ~/.ssh/id_rsa ]; then
    chmod 0600 ~/.ssh/id_rsa
    echo "Permission of id_rsa restored"
fi

if [ -f ~/.ssh/id_rsa_github ]; then
    chmod 0600 ~/.ssh/id_rsa_github
    echo "Permission of id_rsa_github restored"
fi

if [ -f ~/.ssh/id_rsa_zalando ]; then
    chmod 0600 ~/.ssh/id_rsa_zalando
    echo "Permission of id_rsa_zalando restored"
fi
