#!/bin/sh

PROMPT_GLOBAL=$HOME/.dotfiles/scripts/prompt/global.sh
[ -f "$PROMPT_GLOBAL" ] && . "$PROMPT_GLOBAL"

PROMPT_USER="${PROMPT_COLOR_GREEN}\u${PROMPT_COLOR_RESET}"
PROMPT_END="${PROMPT_COLOR_GREEN}\$${PROMPT_COLOR_RESET}"
PS1="${PROMPT_USER} ${PROMPT_PATH}\n${PROMPT_END} "
