#!/bin/sh

# =============================================================================
# MAIN
# =============================================================================

alias ls='exa --git --icons'
alias ll='exa --git --icons -l'
alias la='exa --git --icons -la'
alias ld='exa --git --icons -ld .*' # list only dotfiles
alias lt='exa --git --icons -l -T' # list subfolders as a tree
alias cat='bat'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias diff='colordiff'
alias grep='grep --color=auto'
alias df='df -h'
alias du='du -ch'
alias mkdir='mkdir -pv'
alias rmd='rm -rf' # to remove a dir
alias ping='ping -c 5'
alias tree='tree -C'
alias rename='perl-rename'
alias bashrc='nvim ~/.bashrc && . ~/.bashrc'
alias nvimrc='nvim ~/.config/nvim/init.lua'
alias reload='. ~/.bashrc'
alias dots='cd ~/.dotfiles'
alias edal='nvim ~/.dotfiles/scripts/aliases && . ~/.bashrc'
alias cheat='tldr'
alias htop='btop'
alias sm='btop' # sm = system monitor
alias v='nvim'
alias r='ranger'

bashstats () {
  fc -l 1 | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl | head -n25; 
}

# needs the package "arch-wiki-docs" to be installed on the system
alias archwiki='firefox /usr/share/doc/arch-wiki/html/en/Table_of_contents.html'

# markdown
gg () {
  glow $1 --pager
}

mkcd () {
  mkdir -pv "$1"
  cd "$1" || return
}

alias dead_symlinks='find -L . -type l'

# request a page with a ajax header (search engine testing) #
alias curlajax='curl -H "X-Requested-With: XMLHttpRequest"'
# get web server headers #
alias header='curl -I'

alias now='date +"%T"'
alias c='cal -3w'

camcam () {
  # set default if $1 is empty
  if [ -z "$1" ]
  then
    CAM=0
  else
    CAM=$1
  fi

  mpv "av://v4l2:/dev/video$CAM"
}

slugify () {
  echo "$1" | iconv -c -t ascii//TRANSLIT | sed -r s/[~^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z | xclip -selection c
  # TODO: xclip -o returns wrong value
  echo "$(xclip -o)" "copied to clipboard"
}

# toggle keyboard layout
tk () {
  DE="layout:     de"
  US="layout:     us"
  LAYOUT=$(setxkbmap -query | grep layout)

  if [[ "$DE" == "$LAYOUT" ]]; then
    setxkbmap us
    xmodmap ~/.Xmodmap
    return
  fi

  if [[ "$US" == "$LAYOUT" ]]; then
    setxkbmap de
    return
  fi
}

# =============================================================================
# Package Management
# =============================================================================

alias up='yay -Syu --devel --cleanafter'
alias paclck='su -c "rm /var/lib/pacman/db.lck"'

# =============================================================================
# ARCH-AUDIT
# =============================================================================

audit () {
    echo "# Arch audit:";
    arch-audit
    echo "# Upgradable:";
    arch-audit --upgradable
}

# =============================================================================
# RIPGREP
# =============================================================================

alias rg='rg --type-add="jsx:*jsx"'

# =============================================================================
# PYTHON
# =============================================================================

alias pyserver='python2 -m SimpleHTTPServer'
alias pyclean='find . -name "*.pyc" -delete'

# =============================================================================
# GIT
# =============================================================================

alias g='git'
alias gl='lazygit'
alias lg='lazygit'
alias tig='lazygit'

# bash completion for g - git alias
__git_complete g __git_main

# =============================================================================
# YARN
# =============================================================================

alias y='yarn'
alias zarn='yarn'
alias ys='BROWSER=none yarn start'
alias yd='BROWSER=none yarn dev'
alias yb='yarn build'
alias yt='yarn test'

# =============================================================================
# PNPM
# =============================================================================

alias p='pnpm'
alias pb='pnpm build'
alias pc='pnpm check:code'
alias pt='pnpm test'

# =============================================================================
# NVM - Node Version Manager
# =============================================================================

alias nu='nvm use' # search for .nvmrc and use the defined version
alias nc='nvm current'
alias nl='unset npm_config_prefix && nvm use lts/erbium'

# =============================================================================
# Phillips Hue
# =============================================================================

toggleHueLights () {
  areHueLightsOff=$( lampe -s I | rg off )

  if [ -n "$areHueLightsOff" ];
  then
    echo ""
    notify-send --icon=info "Switch HUE lights ON"
    lampe -s Y
  else
    notify-send --icon=info "Switch HUE lights OFF"
    lampe -s N
  fi
}

