#!/bin/sh

# In nvim use :Vex to open a filelist

alias nt='note today'
alias nq='note quick'

note () {
  NOTES_HOME="$HOME/Cloud.rocks/Notes"

  case "$1" in
    "ls")
      tree "$NOTES_HOME"
      return
      ;;
    "rm")
      rm -i "$NOTES_HOME/$2.md"
      return
      ;;
    "rename")
      mv "$NOTES_HOME/$2.md" "$NOTES_HOME/$3.md"
      return
      ;;
     "find")
      rg "$2" "$NOTES_HOME" "$3"
      return
      ;;
    "view")
      glow "$NOTES_HOME/$2.md" --pager
      return
      ;;
  esac

  # `man test` to get explanation
  if [ -z "$1" ] # is empty?
  then
    $EDITOR "$NOTES_HOME"
    return;
  fi

  $EDITOR "$NOTES_HOME/$1.md";
}
